@startuml

start
group State Initialization
:Flash LEDs purple to signal the start of the state;
:Delay 3 seconds;
:Flash LEDs green to verfiy robot;
:Delay 3 seconds;
end group
group User Authentication
while (User authenticated?) is (no)
    if (User's first attempt?) then (no)
        :Flash LEDs red;
    else (yes)
    endif
    :Pulse LEDs purple to signal gesture detection active;
    :Detect gesture 1;
    :Detect gesture 2;
    :Detect gesture 3;
    :Detect gesture 4;
endwhile (yes)
:Flash LEDs green to signal successful authentication;
end group
stop
@enduml
